#docker-compose.yaml代码
version: "3.8"
services:
  nvidiacuda118:
    container_name: temp2 
    image: nvidia_cuda:11.8.0-cudnn8-devel-ubuntu18.04-v1.0.2.9 
    shm_size: '16gb'
    restart: unless-stopped
    networks:
        mycuda:
           ipv4_address: 172.18.0.100
    ports:
        - "10024:22"
        - "13384:3389"
    volumes:
        - /home/shixian/Downloads:/temp/Downloads
        - /home/shixian/share:/nfs
        - /home/shixian/Projects:/workspace
        - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia  #驱动
              count: "all"
              #count: 1 #或"all"  #数量
              #device_ids: ['0','1','2','3'] #gpu id和 count二选一
              capabilities: [gpu]    #指定需要支持的功能；可以配置多个不同功能
              #capabilities: [gpu, utility] #支持多种功能



networks:
    mycuda:
        name: aihost 
        external: true

volumes:
    aihome:
        # name: aihome
        # external: true



