#docker-compose.yaml代码
version: "3.8"
services:
  nvidiacuda:
    container_name: ai
    image: registry.cn-hangzhou.aliyuncs.com/phzn/nvidia_cuda:pcl-grpc-trtpy-cu113-cudnn8-devel-ubuntu18-v3.2.4
    #command: ["bash", "-c", "/usr/sbin/sshd -D && service xrdp restart"]
    shm_size: '64gb'
    networks:
        mycuda:
           ipv4_address: 172.18.0.4
    ports:
        - "8022:22"
        - "8389:3389"
    volumes:
        - aihome:/home/ai
        - /home/wen/share:/nfs
        - /home/wen/Projects:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia  #驱动
              count: "all"
              #count: 1 #或"all"  #数量
              #device_ids: ['0','1','2','3'] #gpu id和 count二选一
              capabilities: [gpu]    #指定需要支持的功能；可以配置多个不同功能
              #capabilities: [gpu, utility] #支持多种功能

networks:
    mycuda:
        name: aihost 
        external: true

volumes:
    aihome:
        name: aihome
        external: true



