#docker-compose.yaml代码
version: "3.8"
services:
  bj:
    container_name: bj
    image: registry.cn-hangzhou.aliyuncs.com/phzn/nvidia_cuda:pcl-grpc-trtpy-cu113-cudnn8-devel-ubuntu18-v3.2.4
    #command: ["bash", "-c", "/usr/sbin/sshd -D && service xrdp restart"]
    shm_size: '32gb'
    networks:
        mycuda:
           ipv4_address: 172.18.0.10
    ports:
        - "6022:22"
        - "6389:3389"
    volumes:
        - bjhome:/home/ai
        - /home/wen/share:/nfs
        - /home/wen/BJProjects:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia  #驱动
              count: "all"
              #count: 1 #或"all"  #数量
              #device_ids: ['0','1','2','3'] #gpu id和 count二选一
              capabilities: [gpu]    #指定需要支持的功能；可以配置多个不同功能
              #capabilities: [gpu, utility] #支持多种功能


  zh:
    container_name: zh 
    image: registry.cn-hangzhou.aliyuncs.com/phzn/nvidia_cuda:pcl-grpc-trtpy-cu113-cudnn8-devel-ubuntu18-v3.2.4
    #command: ["bash", "-c", "/usr/sbin/sshd -D && service xrdp restart"]
    shm_size: '16gb'
    networks:
        mycuda:
           ipv4_address: 172.18.0.11
    ports:
        - "7022:22"
        - "7389:3389"
    volumes:
        - zhhome:/home/ai
        - /home/wen/share:/nfs
        - /home/wen/ZHProjects:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia  #驱动
              count: "all"
              #count: 1 #或"all"  #数量
              #device_ids: ['0','1','2','3'] #gpu id和 count二选一
              capabilities: [gpu]    #指定需要支持的功能；可以配置多个不同功能
              #capabilities: [gpu, utility] #支持多种功能

networks:
    mycuda:
        name: aihost 
        external: true

volumes:
    bjhome:
        name: bjhome
        external: true
    zhhome:
        name: zhhome
        external: true



