version: '3.8'
services:
  ubuntu_xrdp:
    # image: ubuntu:18.04-xrdp-nasm-v0
    image: registry.cn-beijing.aliyuncs.com/phzn/ubuntu:18.04-xrdp-nasm-v0
    container_name: ubuntu_xrdp
    restart: unless-stopped
    ports:
      - "10023:22"    # 映射 SSH 端口
      - "13390:3389"  # 映射 RDP 端口
    # environment:
    #   - DISPLAY=localhost:10.0
    #   - QT_X11_NO_MITSHM=1
    volumes:
      - /home/shixian/share:/nfs
      - /workspace/ziya:/workspace
      - ./temp:/temp
    command: ["/bin/bash", "-c", "service xrdp restart && /start.sh"] # 设置容器启动命令
    networks:
      - default

networks:
  default:
