# 使用官方Ubuntu 22.04基础镜像
FROM ubuntu:18.04-xrdp-v0
LABEL author=wen \
        version=0 \
        description='ubuntu 18 xrdp xfce4 nasm'
# # 安装nasm
# RUN apt-get install nasm
# # 安装bochs
# RUN apt-get install libx11-dev libc6-dev build-essential xorg-dev libgtk2.0-dev libreadline-dev
# # 安装qemu
# RUN apt-get install qemu
# nasm bochs
RUN apt update \
    && apt install -y nasm \
    && apt-get install -y libx11-dev libc6-dev build-essential xorg-dev libgtk2.0-dev libreadline-dev

ADD bochs-2.7.tar.gz /tmp
RUN cd /tmp/bochs-2.7 \
    && ./configure --with-x11 --with-x --enable-all-optimizations --enable-readline  --enable-debugger-gui --enable-x86-debugger --enable-a20-pin --enable-fast-function-calls --enable-debugger \
    && make \
    && make install \
    && cd /tmp \
    && rm -rf /tmp/bochs-2.7

RUN apt update \
    && apt install -y qemu