#docker-compose.yaml代码
version: "3.8"
services:
  nvidiacuda:
    container_name: faceid
    image: registry.cn-hangzhou.aliyuncs.com/phzn/nvidia_cuda:faceid_mysql-redis_cu113-cudnn8-ubuntu18-v2.1.3
    #command: ["bash", "-c", "/usr/sbin/sshd -D && service xrdp restart"]
    shm_size: '64gb'
    networks:
        mycuda:
           ipv4_address: 172.18.0.6
    depends_on:
        - mysql
        - redis
    ports:
        - "8022:22"
        - "8389:3389"
    volumes:
        - aihome:/home/ai
        - wenquanshanhome:/home/wenquanshan
        - liubaojiahome:/home/liubaojia
        - zhaohenghome:/home/zhaoheng
        - xuezihaohome:/home/xuezihao
        - /nfs/Projects/FaceID:/projects
        - /nfs/Datasets/:/datas
        - /nfs/Saves/:/saves
        - /nfs/Temp/:/temp
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia  #驱动
              count: "all"
              #count: 1 #或"all"  #数量
              #device_ids: ['0','1','2','3'] #gpu id和 count二选一
              capabilities: [gpu]    #指定需要支持的功能；可以配置多个不同功能
              #capabilities: [gpu, utility] #支持多种功能

  mysql:
    image: mysql:latest
    networks: 
        mycuda:
           ipv4_address: 172.18.0.2
    ports:
        - "3306:3306"
    env_file: .env
    volumes:
        - mysqlpath:/var/lib/mysql
    restart: always

  redis:
    image: redis:latest
    #command: ["redis-server", "/etc/redis/redis.conf"]
    networks:
        mycuda:
           ipv4_address: 172.18.0.3
    restart: always
    ports:
        - "6379:6379"
    volumes:
        - redispath:/var/lib/redis
        - redis_confpath:/usr/local/etc/redis
        - redis_datapath:/data


networks:
    mycuda:
        name: nvidia_cuda
        external: true

volumes:
    aihome:
    wenquanshanhome:
    liubaojiahome:
    zhaohenghome:
    xuezihaohome:
    mysqlpath:
    redispath:
    redis_confpath:
    redis_datapath:



